name: ci

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
        #uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        
      #- name: Set up JDK
        #uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        #with:
          #java-version: 21
          #distribution: "temurin"
          #cache: maven
          
      #- name: Build
        #run: mvn -B --no-transfer-progress verify --file pom.xml
        #env:
          #GITHUB_ACTOR: ${{ github.actor }}
          #GITHUB_TOKEN: ${{ secrets.packages-token }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: app
          path: target/*.jar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          push: true
          tags: user/app:latest 
