name: ci

on:
  push:
    branches: [ "master" ]
permissions:
  packages: write
  contents: read

jobs:
  docker-push:
    uses: UzmaSabir/actions/.github/workflows/maven-docker-push.yaml@main
    # permissions:
    #   packages: write
    #   contents: read